### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by karuatcsg** [Microsoft/moodle-auth_oidc#1]
We are trying to use this plug-in to have SSO in Moodle. We use pingfederate OpenID Connect server. Despite configuring the plug-in correctly we are getting errors. Just so we check our configuration, is there any instruction set for configuring the plug-in for pingfederate OpenID Connect server?

**Comment by jamesmcq** [comment]
Hi Karuatcsg - I don't have instructions specifically for other OpenID Connect servers - this plugin is developed against Microsoft Azure. However, the plugin should follow standard OpenID Connect so it should work with standards-based OpenID Connect identity provider. Is there any kind of public pingfederate test service I could try to validate operation against?

**Comment by karuatcsg** [comment]
Thanks for response. We are trying the implementation of OAuth server available at  https://github.com/mitreid-connect/

Hope this is what you asked for.

**Comment by jamesmcq** [comment]
Hi karuatcsg, 

I have not been able to reproduce any problems with a few other OIDC providers, however there have been a lot of updates to this plugin since this was originally reported. Can you update to the latest version and let me know if you are still experiencing issues? If so, do you have any specific error messages you can post?
